### PR TITLE
New scrape engine : HFSDB

### PR DESCRIPTION
**Pull request by fabricecaruso**
The account needs to be injected with -DHFS_DEV_LOGIN=XXXXX

@nadenislamarre : I'm currenly discussing with the HFSPlay Team to have different accounts for Batocera & Retrobat. I'll get back to you with the account information to inject as soon as it's ready.

### CODE REVIEW

**Comment by lbrpdx** [comment]
That is great news, more scraping options, thank you @fabricecaruso !

**Comment by Darknior** [comment]
WOAW so cool they finally give you an access to their API :)
One source more to scrap is always a good news :)
Thanks a lot

**Comment by wadiebs** [comment]
Hello, any update on this one ?
Thank you 🙏

**Comment by fabricecaruso** [comment]
It's been merged for a while now

**Comment by wadiebs** [comment]
But it is not working, seems like username and password are missing
https://github.com/batocera-linux/batocera.linux/issues/5158
Could you please have a look 🙏
Thank you !

**Comment by fabricecaruso** [comment]
It's not on ES side, but on batocera.linux side.
See the issue you mentioned

**Pull request merged**
