### PR TITLE
Threaded model for RetroAchievements.

### PR DESCRIPTION
**Pull request by lbrpdx**
This enables two things:
- having a little "WORKING..." box while the content is being downloaded
- download and display success images/badges (the 1st badge in the list for each game)

The second point needs the updated `batocera-retroachievements-info` script.

### CODE REVIEW

**Comment by lbrpdx** [comment]
Screen Shot 2020-01-24 at 4 09 58 PM

**Comment by fabricecaruso** [comment]
The xml part you updated in ApiSystem for WIN32 testing is invalid & does not compile
```
"<badge>https://s3-eu-west-1.amazonaws.com/i.retroachievements.org/Badge/09025.png</game>"
```
is to be replaced with 
```
"<badge>https://s3-eu-west-1.amazonaws.com/i.retroachievements.org/Badge/09025.png</badge>"
"</game>"

```

- missing this at end ( including ; ):
```
"</retroachievements>"; 
```

**Comment by lbrpdx** [comment]
Truly sorry about this, I did a (too quick) copy and paste, but as you know, I don't compile it under Windows.

**Comment by fabricecaruso** [comment]
It happens to the best of us ;-)

**Pull request merged**
