### PR TITLE
Add "Has Achievements" metadata

### PR DESCRIPTION
**Pull request by shantigilbert**
This will add a metadata option to filter games that use retro achievements. Right now its a manual entry, but I was talking to @fabricecaruso and he will make it a scrapable option for this to be automatic in the future.

### CODE REVIEW

**Comment by shantigilbert** [comment]
FP was to clean up spacing, sorry.

**Comment by fabricecaruso** [comment]
Don't merge it now. It's for Batocera 30

**Comment by Darknior** [comment]
Is it possible to scrap than a game has retroachievement on Screenscrapper ?
Really ? I've never see it before ...

I don't found the information on SS
https://www.screenscraper.fr/gameinfos.php?gameid=192712&action=onglet&zone=gameinfosinfos
But sure the game have Retroachievements
https://retroachievements.org/game/14336

**Comment by lbrpdx** [comment]
@Darknior it’s not from screenscraper, but there is a way to get it directly from the RetroAchievements.org website.

**Comment by fabricecaruso** [comment]
As we discussed on Discord, I close this PR without merging it. 
I cherry picked your commit & it will be part of... A bigger PR....

**Pull request closed without merging**
