### PR TITLE
Spelling, grammar and clarity pass-over

### PR DESCRIPTION
**Pull request by Hew-ux**
Disambiguated some of the more confusing terminology, corrected grammar where appropriate.

### CODE REVIEW

**Comment by nadenislamarre** [comment]
same here for symbols ? :

**Comment by Hew-ux** [comment]
Ah, I changed those where I saw them but didn't explicitly look for them, I may have missed a few. I'll give it another search in a bit.

I also hadn't considered the translation patches, they are hard-coded to the strings they are translating. Should be an easy-enough search & replace. Simple is better. I'll get to that now.

**Comment by evoflash72** [comment]
Could you also group together the many duplicate strings present in the code such as "NONE", "None", "none", "ON", "on", "OFF", "off", etc.

**Comment by Hew-ux** [comment]
@evoflash72 I'm not sure what you mean by that, but I'd like to keep this PR relatively simple until I have more experienced working with Batocera.

**Comment by evoflash72** [comment]
@Hew-ux I think I'll do that later, many duplicated strings to translate in the code (some in uppercase, same as lowercase, etc. in the .po file)

**Comment by Hew-ux** [comment]
ah, I understand what you mean now @evoflash72 , that's something I can take a look at. But for this PR, I'll leave it as it is for now. It's ready to be merged.

**Comment by Hew-ux** [comment]
@nadenislamarre I noticed you updated the fr translation while I was updating the `.po` files, just a heads up

**Comment by Hew-ux** [comment]
merged joinski's de

**Comment by Hew-ux** [comment]
I've now learned of how changes to the English strings affect translations and want to do this properly from the ground up. I'll keep this PR only as a reference for the strings I did change.

**Pull request closed without merging**
