### PR TITLE
[i18n] Add Occitan locale

### PR DESCRIPTION
**Pull request by Mejans**
First commint to add Occitan language

### CODE REVIEW

**Comment by nadenislamarre** [comment]
how do you say Occitan in occitan please ?

**Comment by Mejans** [comment]
Easy, occitan ;)

**Comment by nadenislamarre** [comment]
thanks.

**Comment by nadenislamarre** [comment]
pr done to add oc to es + oc to glibc
- https://github.com/batocera-linux/batocera.linux/pull/1906
- direct commit on es : https://github.com/batocera-linux/batocera-emulationstation/commit/cf6b2ac4b138d86b79d3ced089306e1f5b59402f

so, next builds will get oc ;-)

**Comment by fabricecaruso** [comment]
Don't we need to name it "oc_FR" in ES instead of just "oc" ?

**Pull request merged**
