### PR TITLE
fix: screenscraper jaguar

### PR DESCRIPTION
**Pull request by jdorigao**
Signed-off-by: Juliano Dorigão <jdorigao@gmail.com>

### CODE REVIEW

**Comment by fabricecaruso** [comment]
Hi, 

This could have been achieved differently :

- In es_systems.yml there is not "platorm:" value for jaguar. 
Adding "platform:   atarijaguar" in this file instead would have been a better way to do it. 
"platform" value is meant for that and should be in sync with PlatformId.cpp

- In ES, you don't have to remove old "string" values (these are retropie names), and you can add new ones using the same const value. ( see VIDEOPAC_ODYSSEY2 or SEGA_SG1000, I added multiple names declarations for that console. It's on purpose not to erase retropie names )

{ "atarijaguar",			ATARI_JAGUAR }, -> Doesn't have to be removed.
Just add the new one in the "// batocera specific names" section using the same const :  
{ "jaguar",			ATARI_JAGUAR } without removing the other one, and it will do the job.

**Comment by jdorigao** [comment]
Nice!
Can I leave it to you to make this modification, so would it be the right way?

**Comment by fabricecaruso** [comment]
Which one ??? ;-)

**Comment by jdorigao** [comment]
The jaguar scraper requires {"jaguar", ATARI_JAGUAR}

**Comment by fabricecaruso** [comment]
You have a second PR with it !?

**Pull request closed without merging**
