### PR TITLE
Update emulationstation2.pot

### PR DESCRIPTION
**Pull request by DDinghoya**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
hi,
the pot file is an automatically updated file.
for batocera translations, go here : https://translations.batocera.org/

**Comment by DDinghoya** [comment]
> hi, the pot file is an automatically updated file. for batocera translations, go here : https://translations.batocera.org/

Thank you for your strong support!

Previously I had committed to github twice and it was reflected. After being informed, I am registering according to the translation site's procedures.

I think my ID (DDinghoya) should be registered as a translator on https://translations.batocera.org/

Can you decide? Or is there another way?

**Comment by nadenislamarre** [comment]
yes, for which language ?

**Comment by DDinghoya** [comment]
> yes, for which language ?

Korean on translation site. :)

**Pull request closed without merging**
