### PR TITLE
add challenge indicator option to retroachievements section

### PR DESCRIPTION
**Pull request by Hew-ux**
complements https://github.com/batocera-linux/batocera.linux/pull/5156

### CODE REVIEW

**Comment by fabricecaruso** [comment]
@nadenislamarre  Ok for me. You can merge this one as soon as the other PR is merged into batocera-linux

**Comment by nadenislamarre** [comment]
but why don't we use the feature file ?

**Comment by Hew-ux** [comment]
> but why don't we use the feature file ?

I'm not sure what you mean, this is just a toggle option in RetroArch (when RetroAchievements are enabled).

**Comment by Darknior** [comment]
Yes it is the same solution we already using for other Retroachievement options, i think it is the good one.

**Comment by nadenislamarre** [comment]
there is a es_features.yml file to declare features. why to not use it.
for existing es lr feature, we must move them to the file too.

**Comment by Hew-ux** [comment]
I don't think we're on the same page here. Any system that supports RetroAchievements will have challenge indicators on by default. This is a toggle to turn that off, just like with other settings related to RetroAchievements like leaderboards, auto-screenshot, etc.

If you'd like to see an example, refer to https://github.com/batocera-linux/batocera.linux/pull/5156 as mentioned in the first post. This is something you would see in any system that supports RetroAchievements when RetroAchievements are activated.

**Comment by nadenislamarre** [comment]
@Hew-ux options for es should not be defined in es while there are specific to batocera,
they should be defined here : https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_features.yml

**Comment by Darknior** [comment]
@nadenislamarre Retroachievement options have never been write in es_features ?
Only in the "libretroConfig.py " file ... 
I speak for Python code. Libretro options about Retroachievements are not in es_features for sure.
There we only tag "cheevos" or not, no more

**Comment by Hew-ux** [comment]
I'm pretty confused now. @nadenislamarre if you could show me the code implementation of what you are suggesting I'd probably understand it better.

**Comment by fabricecaruso** [comment]
@nadenislamarre Retroachievement screen is not a game/system option screen, so it's not dependant on es_features. 
There's no way we can implement this with es_features for now.

As the other PR is merged. I merge this one.

**Pull request merged**
