### PR TITLE
add: screenscraper jaguar

### PR DESCRIPTION
**Pull request by jdorigao**
Signed-off-by: Juliano Dorigão <jdorigao@gmail.com>

### CODE REVIEW

**Comment by jdorigao** [comment]
@fabricecaruso Would that be the right form?

**Comment by fabricecaruso** [comment]
Why did you open a second PR ? Is it a mistake ?

**Comment by jdorigao** [comment]
To make the jaguar scraper you need a jaguar platform and not a atarijaguar

**Comment by fabricecaruso** [comment]
As I said, this is because in "es_systems.yml" there is not "platform:" value for jaguar. It should be "platform: atarijaguar".
Anyway, we can add this one.

**Pull request merged**
