### PR TITLE
Update preload labels in dev options

### PR DESCRIPTION
**Pull request by Hew-ux**
PRELOAD UI > PRELOAD UI ELEMENTS (Reduce overall menu lag at the cost of storage space)
PRELOAD MEDIAS FILESYSTEM (REDUCE UI LAGS OVER STARTUP TIME) > PRELOAD METADATA MEDIA (Reduce gamelist lag at the cost of storage space)

### CODE REVIEW

**Comment by nadenislamarre** [comment]
i think that all strings are uppercase (of almost all) in es

**Comment by Hew-ux** [comment]
Most are. Deceptive labels have not been (you know, the smaller text underneath the main label.) Eg. any option in advanced per system settings, the "swap confirm and cancel buttons" option (in that same dev many mind you), etc.

Either this all caps is changed to regular casing, or all the other hundred or so descriptive labels are changed to all caps. I think the former is quicker.

**Comment by fabricecaruso** [comment]
@Hew-ux @nadenislamarre 

"at the cost of storage space" ???? Seriously !?
That's **absolutely not** what happens and the label you changed/added are now totally wrong !!!

"PRELOAD UI" Preloads the gamelist UIs ( instead of doing a lazy loading ) -> Either it takes more time @ startup. Either it introduce lags 1st time you enter a gamelist.

"PRELOAD METADATA MEDIA" -> Either it takes more time @ startup checkin' if media files exist. Either medias files existance is checked only when required which can produce lags when browsing the UI.

Please fix the labels.

**Comment by Hew-ux** [comment]
Noted, I'll make a new PR that fixes these labels.

**Pull request merged**
