### PR TITLE
on/auto/off for switches

### PR DESCRIPTION
**Pull request by nadenislamarre**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
file:///tmp/screenshot-2024.09.08-23h04.45.png

**Comment by nadenislamarre** [comment]
screenshot-2024 09 08-23h04 45

**Comment by nadenislamarre** [comment]
personnally, i like the "auto" value lost with the simple on/off switches.
but maybe this 3 ways switch is not clear.

**Comment by Tovarichtch** [comment]
Middle switch position value is `auto`? Any way to make it clear like in small character under, or beside it? So it changes in real time?

**Pull request merged**
