### PR TITLE
Region detection improvements

### PR DESCRIPTION
**Pull request by geogolem**
See the discussion here: 
https://github.com/batocera-linux/batocera-emulationstation/issues/1686

### CODE REVIEW

**Comment by geogolem** [comment]
> It's a bad solution to use getString("ThemeRegionName") in the extractLang method, most themes don't use/define regions. It would work with a very limited number of themes.

I totally get what you are saying. I was trying to make use of the existing options etc. so as to avoid having the user specify a preferred Region --> since this is sort of already specified in the GUI Options -- at least when I was testing -- but I am not that familiar with too many themes.. etc.

Having the check for the locale actually resolves all my test issues where I was running into this problem i.e. 1080 Snowboarding (Japan, USA) (En,Ja)

The locale check would make it pick USA over Japan for me or vice versa but I anticipated cases where there could be both USA and Europe in the region list.. which is possible in the nointro naming scheme.. Then the locale specification wouldn't be enough to differentiate.. whereas the themeregion settings which I saw in the GUI options on Batocera would...

in [es-core/src/ThemeData.cpp](https://github.com/batocera-linux/batocera-emulationstation/blob/27b3594d68ffb68f28cde23cb43c350e5023a561/es-core/src/ThemeData.cpp#L686)
there is a check and a default region used: 
```
mRegion = Settings::getInstance()->getString("ThemeRegionName");
if (mRegion.empty()) mRegion = "eu";
```
Maybe having a similar check to handle this case would improve the code. 

I need to have a look at how Batocera treats this ThemeRegion setting when using different themes --> if the setting is still under GUI Options.. then it should work fine --> but should still have the check for if its empty, then dont use it (i.e. falling back on the locale specification only)

I appreciate your feedback --> I'll look more into it later tonight or tomorrow. 

Just thought I would respond indicating my thoughts on it in case you had any further feedback or suggestions.. I mean, ultimately we could make a distinct option for region preference specification that could be used.. but I thought it would be better to piggy back on the existing options if possible... maybe.

**Comment by fabricecaruso** [comment]
I don't think it's necessary to add a new option for the "prefered region". It's already possible to deduct the region based on "system.language". Creating a table of regions for this value should be enough ( en_GB : it's Europe... en or empty is US. pt_PT is Europe. pt_BR is brazil, eu_ES is europe, es_MX is south america... )

In my POV, Either :
- You make it simple and extract the user's region from the system.language value, then import the best region based on this data when you have multiple regions.
- Either you import every possible regions into a comma delimited string ( or ; ). In that case, it required some other changes in the code : the region flag image is to be computed : either it's the best calculated one (using ThemeRegion) or the one from system.language, either the first one.

**Comment by geogolem** [comment]
> * You make it simple and extract the user's region from the system.language value, then import the best region based on this data when you have multiple regions.

> * Either you import every possible regions into a comma delimited string ( or ; ). In that case, it required some other changes in the code : the region flag image is to be computed : either it's the best calculated one (using ThemeRegion) or the one from system.language, either the first one.

I think storing all the possible regions into a comma delimited string is the better solution simply for completeness; however, just importing the best region using the locale info is still an improvement and more than "good enough" in my opinion...

**Comment by fabricecaruso** [comment]
With French language (and many others), getSystemRegion returns an empty string, so your code is not working with many regions.

**Comment by geogolem** [comment]
> With French language (and many others), getSystemRegion returns an empty string, so your code is not working with many regions.

its been a minute since I looked at this.. so I'll need to confirm what I'm writing here.. 

but getSystemRegion only needs to handle those regions where languages could correspond to multiple regions or where the region cannot be immediately determined from the language. 

With Korea the issue is Kr vs. Ko etc. and with Portugeses it can be either Brazil or European depending on pt_PT, or pt_BR

For example, with French, the langData specification specifies Europe as the region for language fr. 

this is taken care of in the second branch of the if statement:
```
						if ((region != systemRegion) && langData.region == systemRegion)
						{
							region = langData.region;
							}
						else if (((region != systemRegion) || systemRegion.empty()) && (langData.lang == systemLang))
						{
							region = langData.region;
						}
```

for example, with english(us) vs. english(gb) just the language is not enough to determine the region.. therefore getSystemRegion needs to handle that.. with fr_Fr, just the language fr is enough to determine the region in langData.

The idea is that getSystemRegion doesn't need to be exhuastive.. if it returns an empty string, it all still works.. because the systemLang is used instead.

For example, French should still all work as expected.. I think.. as i said its been a while so I will look more into it at some point.

**Comment by geogolem** [comment]
> With French language (and many others), getSystemRegion returns an empty string, so your code is not working with many regions.

its been a minute since I did this --> however, the fact that it returns an empty string for many cases is intended... as the code fallse back on systemLanguage if systemRegion is empty... In most cases, the proper region can be deduced from the language and is already specified in langData --> however, in some cases, like english the preferred region cannot be determined.. i.e. is it eu or us?

in those cases, it is necessary... having said that.. I will commit a few changes that will make the code more complete although functionally won't change anything..

**Comment by geogolem** [comment]
The code now basially will implement every region/language combination as specified in: 
[es-app/src/guis/GuiMenu.cpp](https://github.com/batocera-linux/batocera-emulationstation/blob/aa240ebac79c6a2463d6dd01ad4d4498fdafc858/es-app/src/guis/GuiMenu.cpp#L1124)

**Comment by fabricecaruso** [comment]
Now, getSystemRegion returns "_fr", so it will probably never work for every language except for "gb", "pt" and "es"...
Also, getSystemLang has no default "return".
You also don't need to "else" a condition that performs a "return".

Testing your code with about 20000 filesnames, I have NO case where the code reaches one of your new assignements with most languages ( fr, it, de... ) and I have only one case with US english.

Can you provide a list of working test cases ?

**Comment by geogolem** [comment]
> Now, getSystemRegion returns "_fr", so it will probably never work for every language except for "gb", "pt" and "es"... Also, getSystemLang has no default "return". You also don't need to "else" a condition that performs a "return".
> 
> Testing your code with about 20000 filesnames, I have NO case where the code reaches one of your new assignements with most languages ( fr, it, de... ) and I have only one case with US english.
> 
> Can you provide a list of working test cases ?

in the most recent commit be fore your comment I neglected to strip off the leading _ in the language which is the reason for the _fr which is why most of your tests hit the new assignments.

I since pushed 2 commits. First stipping off the leading _ and a subsequent one that better handles regions like Fr etc.

Below are examples of the types of cases, I personally aimed to fix: 
1080 Snowboarding (Japan, USA) (En,Ja)  
Without my code, region is Japan (first/only hardRegion detected).
With my code hardRegion USA is also detected:
In the case of English(US), USA is selected based on matching systemRegion (first branch of if statement).
In the case of English(UK), USA is selected based on matching systemLang (second branch of if statement)
For other locales like French, neither the region or language match so the behavior is unchanged from without my code. i.e. region is Japan which was the first one found.

Alex Kidd in Miracle World (USA, Europe, Brazil) (En) (Rev 1)
Without my code, region is USA (first/only hardRegion detected).
With my code hardRegions Europe and Brazil are also detected:
In the case of English(US), USA will be selected based on matching systemRegion
In the case of English(UK) Europe will be selected based on matching systemRegion
In the case of pt_BR, Brazil will be selected
For other locales like French, Europe will be selected based on matching systemRegion (note the systemRegion is adjusted based on langData.region) - since fr_Fr for the locale doesn't actually specify EU; however, for langData matching fr the langData.region is Eu.

The master system actually had many other examples similar to the last one.. but for the n64 the 1080 snowboarding is the only one I initially had an issue with...

**Comment by geogolem** [comment]
I cleaned up the code a bit.. as I dont really see a need to have functions getSystemLang or getSystemRegion etc. i.e. basically it is just splitting the string at _ and the first part if the language, second part is the region and then the region needs to be adjusted based on the langData's used in the existing region detection code.

**Comment by geogolem** [comment]
The code is alot simpler now and it now implements cases like fr corresponding to eu properly which I had previously overlooked.

**Comment by geogolem** [comment]
The code is alot simpler now and it properly implements cases like fr corresponding to eu properly which I had previously overlooked.

I appreciate your feedback. It had been a minute since I originally did this, but your comments/feedback made me re-evaluate how it was implemented.. Hopefully it makes more sense now.

I am writing up a test suite.. so stay tuned for that...

EDIT: also --> the code handles the case where the system locale is for example English(UK) and the romname is romName (Japan, USA)... region US will be chosen not because the systemRegion matches directly but because no direct systemRegion match was found but USA corresponds to english which does match the system language..

small test suite coming soon --> just writing/verifying it now... will post again soon.

**Comment by geogolem** [comment]
Test rom files:

romName1 (Japan, USA).ext
romName2 (Japan, USA, Europe, Brazil).ext
romName3 (Japan, Brazil, Europe).ext

Before the code changes, all of these would set region to Japan regardless of System Locale.

SystemLocale --> English(US) --> en_US
romName1 (Japan, USA).ext ---> region ==> USA
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> USA
romName3 (Japan, Brazil, Europe).ext ---> region ==> Europe

systemLocale --> English(UK) --> en_GB
romName1 (Japan, USA).ext ---> region ==> USA
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> Europe
romName3 (Japan, Brazil, Europe).ext ---> region ==> Europe

systemLocale --> FRANÇAIS--> fr_FR
romName1 (Japan, USA).ext ---> region ==> Japan
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> Europe
romName3 (Japan, Brazil, Europe).ext ---> region ==> Europe

systemLocale --> Japanese --> ja_JP
romName1 (Japan, USA).ext ---> region ==> Japan
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> Japan
romName3 (Japan, Brazil, Europe).ext ---> region ==> Japan

systemLocale --> PORTUGUÊS BRASILEIRO--> pt_BR
romName1 (Japan, USA).ext ---> region ==> Japan
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> Brazil
romName3 (Japan, Brazil, Europe).ext ---> region ==> Brazil

systemLocale --> PORTUGUÊS PORTUGAL--> pt_PT
romName1 (Japan, USA).ext ---> region ==> Japan
romName2 (Japan, USA, Europe, Brazil).ext ---> region ==> Europe
romName3 (Japan, Brazil, Europe).ext ---> region ==> Europe

**Pull request merged**
