### PR TITLE
fix br flag

### PR DESCRIPTION
**Pull request by azvarel**

### CODE REVIEW

**Comment by Darknior** [comment]
We must not add it, we must rename it from BZ to BR and i think add PT flag because i miss it

**Comment by coiotato** [comment]
PT flag will be added too? :)

**Comment by Darknior** [comment]
i don't know, i stand @fabricecaruso ask me if i must draw some new flags. For the moment PT flag is not created because i never found any PT game, only BR games.

**Comment by fabricecaruso** [comment]
As discussed on discord, this renaming will be included in my next PR, so I close this PR.

**Pull request closed without merging**
