### PR TITLE
minor corrections to "gun tolerence" and bluetooth related labels

### PR DESCRIPTION
**Pull request by Hew-ux**

### CODE REVIEW

**Comment by Darknior** [comment]
Thanks, "PAIR A BLUETOOTH DEVICE FROM A LIST" is really better :)

**Comment by nadenislamarre** [comment]
yes, i agree.
to be merged after b36 released.

**Comment by n2qz** [comment]
This never got merged, any chance of it making it into Batocera v39?

**Comment by nadenislamarre** [comment]
yes we can (but needs rebase)

**Pull request closed without merging**
