### PR TITLE
Added additional formats for background music

### PR DESCRIPTION
**Pull request by lbrpdx**
Background music: added support for .flac, .wav and popular .mod chiptune formats (.mod, .xm., .stm, .s3m, .far, .it, .mtm, .669...)

(Fixed previous crappy PR)

### CODE REVIEW

**Comment by mistepien** [comment]
I got this:
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libSDL2main.a;/data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libSDL2.so;-lpthread  
-- Found CURL: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcurl.so (found version "7.67.0") 
-- Checking for module 'libvlc>=1.0.0'
--   Found libvlc, version 3.0.8
-- VLC library found
-- Found VLC: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/vlc  
-- Found Rapidjson: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include  
-- Looking for libCEC...
-- Checking for module 'libcec'
--   Found libcec, version 4.0.4
-- Found libCEC: optimized;/data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcec.so;debug;/data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libcec.so
-- Found ALSA: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libasound.so (found version "1.2.1.1") 
-- Found Intl: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include  
-- Native language support enabled.
CMake Error at external/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/build/batocera-emulationstation-1cb2514cf1cecce9e37b3bde88df3427f9113706/external/pugixml

  does not contain a CMakeLists.txt file.


Building the pot file
LANG = ar
LANG = ca
LANG = de
LANG = el
LANG = es
LANG = es_MX
LANG = eu_ES
LANG = fr
LANG = hu
LANG = it
LANG = jp_JP
LANG = ko
LANG = nb_NO
LANG = nl
LANG = nn_NO
LANG = pl
LANG = pt_BR
LANG = pt_PT
LANG = ru_RU
LANG = sv_SE
LANG = tr
LANG = zh_CN
LANG = zh_TW
-- Configuring incomplete, errors occurred!
See also "/data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/build/batocera-emulationstation-1cb2514cf1cecce9e37b3bde88df3427f9113706/CMakeFiles/CMakeOutput.log".
See also "/data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/build/batocera-emulationstation-1cb2514cf1cecce9e37b3bde88df3427f9113706/CMakeFiles/CMakeError.log".
make[1]: *** [package/pkg-generic.mk:252: /data2/misc/BATOCERA/testowo/batocera.linux/output/rpi3/build/batocera-emulationstation-1cb2514cf1cecce9e37b3bde88df3427f9113706/.stamp_configured] Error 1
make: *** [Makefile:23: _all] Error 2

**Comment by mistepien** [comment]
I have this file:
[flac]{https://www.dropbox.com/s/wlzfzxwmng5v64t/R1-D1_Unit_Attack.flac?dl=0}

and it does not work.

**Comment by lbrpdx** [comment]
Seems like the FLAC encoding you have is not compatible with SDL2 mixer. Strange it's coded in mono.
I tested a bunch of FLAC files, for example from freely available at http://www.2l.no/hires/ and they seem to work.

**Comment by lbrpdx** [comment]
SDL2_mixer library can be touchy sometimes. We've also gotten reports of .mp3 that were not correctly decoded either... but there is not a lot we can do on ES, we're depending it for the audio decoding part.

**Comment by mistepien** [comment]
I have ogg file and flac file. Ogg is encoded with oggenc and flac with flac command.
This is wav file:
General
Complete name                            : new.wav
Format                                   : Wave
File size                                : 12.8 MiB
Duration                                 : 2 min 32 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 706 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 2 min 32 s
Bit rate mode                            : Constant
Bit rate                                 : 705.6 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 12.8 MiB (100%)


This is ogg file:
General
Complete name                            : new.ogg
Format                                   : Ogg
File size                                : 4.40 MiB
Duration                                 : 2 min 32 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 243 kb/s

Audio
ID                                       : 1921722554 (0x728B28BA)
Format                                   : Vorbis
Format settings, Floor                   : 1
Duration                                 : 2 min 32 s
Bit rate mode                            : Variable
Bit rate                                 : 160 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Compression mode                         : Lossy
Stream size                              : 2.90 MiB (66%)
Writing library                          : libVorbis (Now 100% fewer shells) (20180316 (Now 100% fewer shells))

and this is flac file:
General
Complete name                            : new.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 6.60 MiB
Duration                                 : 2 min 32 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 364 kb/s

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 2 min 32 s
Bit rate mode                            : Variable
Bit rate                                 : 364 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 6.59 MiB (100%)
Writing library                          : libFLAC 1.3.3 (UTC 2019-08-04)

ogg has 1 channel, as well flac, and ogg file works but flac does not.

But anyway I will test flac file with two fake channels.

**Comment by mistepien** [comment]
Ok, stereo flac file works, but mono flac doesn't work. But mono ogg file works fine.
Mono flac files is not something rare in that case. My mono flac files was made from sid file. Most of sid files are mono, especially from the epoque.

**Pull request merged**
