### PR TITLE
Add system menu option to view controller overlay

### PR DESCRIPTION
**Pull request by wizzomafizzo**
This adds a menu option to the system menu for viewing its controller overlay image. I would rather not hardcode the path but I couldn't see where/if this path is defined.

It's not ready to go in until high res overlay images have been included in the image (works fine but looks like crap)

### CODE REVIEW

**Comment by fabricecaruso** [comment]
For your information : 
As EmulationStation has to be portable ( Paths must exist also on Windows, with EmuElec, RetroLX, etc... )
I'm currently refactoring the whole "paths thing" to have only one cpp file storing every "known" paths. 
You can see my work branch for my next PR including this code there :
https://github.com/fabricecaruso/batocera-emulationstation/blob/win/es-core/src/Paths.cpp#L20

In consequence, I won't accept new PRs with code using specific paths like this ( /usr/share/batocera/controller-overlays ), unless declared outside this class.

Maybe wait for my next PR to finish yours...

**Comment by wizzomafizzo** [comment]
Oh that is a much better idea. Yes happy to wait for that to go in and then update this later

**Comment by fabricecaruso** [comment]
Will you finish this PR ?

**Comment by wizzomafizzo** [comment]
No plans to. Feel free to close if nobody else wants to implement

**Pull request closed without merging**
