### PR TITLE
Bump NanoSVG to Latest Version

### PR DESCRIPTION
**Pull request by shinzon76**
Updated NanoSVG to latest version for bug fixes, security fixes and new features

### CODE REVIEW

**Comment by nadenislamarre** [comment]
@fabricecaruso ?

**Comment by fabricecaruso** [comment]
Does not compile. 
There's a bad closing }

**Comment by shinzon76** [comment]
Might be related to the optimizations i ported over from the old NanoSVG version. Let me look into it and i'll update the branch

**Comment by fabricecaruso** [comment]
Are you gonna fix this ?

**Pull request closed without merging**
