### PR TITLE
Almost complete emulationstation catalan translation

### PR DESCRIPTION
**Pull request by joao-pedro-barbosa**

### CODE REVIEW

**Comment by Hew-ux** [comment]
Very robust translation! Just a few things:

The following words are proper nouns (the name of something) and should not be translated:
Retroachievements, gamelist, all the screenscraper image options.

Also, entire strings that don't need to be translated don't need to have a specific `msgstr` attached to them. The fallback behaviour is to show the default language's string anyway. No harm in doing it, but it can save you work in the future translations.

**Comment by joao-pedro-barbosa** [comment]
Thank you for your comments. I'll take a look and improve it. :)

**Comment by joao-pedro-barbosa** [comment]
Just a thing. I saw other strings translated from other people and I tried to give some consistency maintaining other people changes.
Can I apply the changes you tell me overwriting previous translated strings from others, as necessary?

**Comment by joao-pedro-barbosa** [comment]
Finally I decided to translate or copy some strings to target language (in english) just to say "that's the way we want to translate it" and reach near 100% of translation and mark as discussed the string.
If you decide that's good and that cannot break anything, we can merge into master, and I'll take a look testing the translation and refining it after testing.

**Comment by nadenislamarre** [comment]
this is the good way to do. thanks for you work.

**Comment by Hew-ux** [comment]
Looks good, very nice work!

**Comment by nadenislamarre** [comment]
i have fixed the file in a later commit. at leqst 20 strings were duplicated. not a big deal.

**Comment by joao-pedro-barbosa** [comment]
> i have fixed the file in a later commit. at leqst 20 strings were duplicated. not a big deal.

Mi apologies @nadenislamarre and @Hew-ux. Must be an incoming merge I did. Thanks for fix-it.

**Pull request merged**
